---
ws_listen_address: 0.0.0.0
ws_listen_port: 5678
http_listen_address: 0.0.0.0
http_listen_port: 8080
allowed_commands:
- "^ping"
- "^cat /etc/hosts"
- "^cat /etc/resolv.conf"
- "^ip route$"
- "^ip addr$"
- "^ip link$"
- "^ip neigh"
- "^netstat"
- "^dig"
- "^traceroute"
- "^curl"
- "^whois"
- "^kubectl"
- "^iperf"