apiVersion: v1
kind: ConfigMap
metadata:
  name: diag-container-config
data:
  allowed_commands: |
    ["^ping", "^cat /etc/hosts", "^cat /etc/resolv.conf", "^env$", "^ip route$", "^ip addr$", "^ip link$", "^ip neigh", "^netstat", "^dig", "^nc", "^ab", "^siege", "^tcping", "^traceroute", "^tcptraceroute", "^curl", "^whois", "^kubectl", "^iperf"]
  host_entries: |
    104.21.192.109    ifconfig.io
  http_listen_address: "0.0.0.0"
  http_listen_port: "8080"
  ws_listen_address: "0.0.0.0"
  ws_listen_port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diag-container-app
spec:
  selector:
    matchLabels:
      app: diag-container-app
  replicas: 1
  template:
    metadata:
      labels:
        app: diag-container-app
    spec:
      volumes:
      - name: diag-container-volume
        configMap:
          name: diag-container-config
      containers:
      - name: diag-container
        image: jgruberf5/container-demo-runner:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        volumeMounts:
        - name: diag-container-volume
          mountPath: /etc/container-demo-runner
        env:
        - name: HTTP_CLIENT_PORT
          value: "31080"
        - name: WS_CLIENT_PORT
          value: "31080"
        - name: IPERF_CLIENT_PORT
          value: "31001"
---
apiVersion: v1
kind: Service
metadata:
  name: diag-container-web-in-cluster
spec:
  type: ClusterIP
  selector:
    app: diag-container-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: diag-container-web
spec:
  type: NodePort
  selector:
    app: diag-container-app
  ports:
  - name: http
    port: 8080
    nodePort: 31080
---
apiVersion: v1
kind: Service
metadata:
  name: diag-container-iperf-in-cluster
spec:
  type: ClusterIP
  selector:
    app: diag-container-app
  ports:
  - name: http
    port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: diag-container-iperf
spec:
  type: NodePort
  selector:
    app: diag-container-app
  ports:
  - name: http
    port: 5001
    nodePort: 31001
